language: java
install: true

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew
addons:
  sonarcloud:
    organization: "sonarcloud_organization_key" # the key of the org you chose at step #3
    token:
      secure: "b6ab64494e5868a9b40b468ce24f6945739fb3c4" # encrypted value of your token
    script:
      # other script steps might be done before running the actual analysis
      - sonar-scanner
script:
  #- ./gradlew sonarqube -Dsonar.projectKey=github-purple_codebeate-test -Dsonar.organization=github-purple-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=
  - ./gradlew build
