language: java
install: true

jdk:
  - oraclejdk8

before_script:
  - chmod +x gradlew
script:
  - ./gradlew sonarqube -Dsonar.projectKey=github-purple_codebeate-test -Dsonar.organization=github-purple-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=b6ab64494e5868a9b40b468ce24f6945739fb3c4
  - ./gradlew build
